# Generated by Django 3.1.2 on 2020-10-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20201016_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.activity')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('ownership', models.CharField(choices=[('o', 'Own'), ('c', 'Collaboration'), ('e', 'External')], default='o', max_length=1)),
                ('status', models.CharField(choices=[('p', 'Published'), ('d', 'Draft'), ('c', 'Cancelled')], default='p', max_length=1)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('timetable', models.CharField(blank=True, max_length=2000)),
                ('partners', models.CharField(blank=True, max_length=1000)),
                ('online', models.BooleanField(default=False)),
                ('tickets', models.BooleanField(default=False)),
                ('fees', models.CharField(blank=True, max_length=1000)),
                ('particip_num_predict', models.IntegerField(blank=True, null=True)),
                ('particip_num_actual', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('registr_link', models.URLField(blank=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
