# Generated by Django 3.1.2 on 2020-10-19 12:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audiences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'young kids'), (2, 'youth'), (3, 'seniors')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'architecture'), (2, 'heritage'), (3, 'cultural education'), (4, 'cinema'), (5, 'photography'), (6, 'video games'), (7, 'interdisciplinary'), (8, 'cabaret'), (9, 'cuisine'), (10, 'literature'), (11, 'fashion'), (12, 'music'), (13, 'new media'), (14, 'traveling'), (15, 'desing'), (16, 'urban intervension'), (17, 'craft'), (18, 'street art'), (19, 'visual arts'), (20, 'dance'), (21, 'theatre'), (22, 'other')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
