# Generated by Django 3.1.2 on 2020-10-21 09:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_auto_20201019_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('architecture', 'architecture'), ('heritage', 'heritage'), ('cultural education', 'cultural education'), ('cinema', 'cinema'), ('photography', 'photography'), ('video games', 'video games'), ('interdisciplinary', 'interdisciplinary'), ('cabaret', 'cabaret'), ('cuisine', 'cuisine'), ('literature', 'literature'), ('fashion', 'fashion'), ('music', 'music'), ('new media', 'new media'), ('traveling', 'traveling'), ('design', 'desing'), ('urban intervension', 'urban intervension'), ('craft', 'craft'), ('street art', 'street art'), ('visual arts', 'visual arts'), ('dance', 'dance'), ('theatre', 'theatre'), ('other', 'other')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timetable',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
