# Generated by Django 3.1.2 on 2020-11-04 14:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201021_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audiences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('young kids', 'young kids'), ('primary school', 'primary school'), ('teenagers', 'teenagers'), ('students', 'students'), ('adults', 'adults'), ('seniors', 'seniors'), ('all', 'all')], max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
