# Generated by Django 3.1.3 on 2020-11-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location'),
        ('projects', '0006_auto_20201116_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='multiple_locations',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
