# Generated by Django 3.1.4 on 2020-12-15 10:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location'),
        ('organizations', '0006_organization_short_name'),
        ('projects', '0009_auto_20201120_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('disadvantaged groups', 'disadvantaged groups'), ('people with disabilities', 'people with disabilities'), ('district residents', 'district residents'), ('pupils', 'pupils'), ('artists / creators', 'artists / creators'), ('event organizers', 'event organizers'), ('ngo representatives', 'ngo representatives'), ('educators', 'educators'), ('activists', 'activists')], max_length=147, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='municipal_programs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Akacja Lato w mieście', 'Akacja Lato w mieście'), ('Akcja Zima w mieście', 'Akcja Zima w mieście'), ('Dla seniorów', 'Dla seniorów'), ('Katowice bez barier', 'Katowice bez barier'), ('Wydarzenie okolicznościowe', 'Wydarzenie okolicznościowe')], max_length=102, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outside_funders',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='outside_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('architecture', 'architecture'), ('heritage', 'heritage'), ('cultural education', 'cultural education'), ('ecology', 'ecology'), ('cinema', 'cinema'), ('photography', 'photography'), ('video games', 'video games'), ('interdisciplinary', 'interdisciplinary'), ('cabaret', 'cabaret'), ('cuisine', 'cuisine'), ('folk/local culture', 'folk/local culture'), ('literature', 'literature'), ('fashion', 'fashion'), ('music', 'music'), ('science', 'science'), ('new media', 'new media'), ('traveling', 'traveling'), ('design', 'desing'), ('urban intervension', 'urban intervension'), ('craft', 'craft'), ('street art', 'street art'), ('visual arts', 'visual arts'), ('dance', 'dance'), ('theatre', 'theatre'), ('other', 'other')], max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.activity'),
        ),
    ]
