# Generated by Django 3.1.4 on 2020-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201215_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('d', 'Draft'), ('c', 'Cancelled')], default='p', max_length=1),
        ),
    ]
