# Generated by Django 3.1.3 on 2020-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20201016_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
