version: '3.7'

services:
  web:
    env_file:
      - config/.env
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mdillon/postgis:11-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
