version: '3.7'

services:
  web:
    env_file:
      - config/.env
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/website
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
