version: '3.7'

services:
  web:
    build: .
    command: gunicorn event_manager.wsgi -b 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mdillon/postgis:11-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
